zwierzeta=list()
zwierzeta.extend(["dog","women","cat","lion","mouse","fly","chicken"])
zwierzeta.sort()
print(zwierzeta)
print( )
zwierzeta=list()
zwierzeta.extend(["dog","women","cat","lion","mouse","fly","chicken"])
print(zwierzeta[0:3] ,zwierzeta[4:8])
print(len(zwierzeta))